name: mt3-torch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - pytorch-lightning=2.5.2
  - matplotlib=3.10
  - numpy=2.2
  - scipy=1.15
  - pandas=2.3
  - librosa=0.11.0
  - fsspec=2025.5.1
  - tqdm=4.67
  - requests=2.32
  - pyyaml=6.0
  - pip=25.1
  - pip:
      - pretty-midi==0.2.10
      - note-seq==0.0.5
      - wandb==0.20.1
      - hydra-core==1.3.2
      - scikit-learn==1.7.0
      - numba==0.61.2
      - pydub==0.25.1
      - omegaconf==2.3.0
