data:
  manifest_path: manifests/manifest_20250712_135419.json

  batch_size_per_device: 16
  num_workers: 8
  segment_seconds: 2.048
  temperature: 0.3

  spectrogram_config:
    sample_rate: 16000
    hop_width: 256
    num_mel_bins: 229

  ignore_program: true
  debug: false