eval:
  checkpoint: lightning_logs/version_4/checkpoints/epoch-045.ckpt
  hparams_yaml: lightning_logs/version_4/hparams.yaml
  accelerator: gpu
  devices: [0]
  eval_one: false  
  segment_batch_size: 32

defaults:
  - data
  - _self_
