data:
  manifest_path: manifests/manifest_20250712_135419.json

  batch_size_per_device: 6
  num_workers: 16
  segment_seconds: 10.0
  temperature: 0.3

  spectrogram_config:
    sample_rate: 16000
    hop_width: 256
    num_mel_bins: 229