data:
  manifest_path: manifests/manifest_20250711_150729.json

  batch_size: 4
  num_workers: 8
  segment_seconds: 4.0
  temperature: 0.5

  spectrogram_config:
    sample_rate: 16000
    hop_width: 256
    num_mel_bins: 64