eval:
  checkpoint: lightning_logs/version_0/checkpoints/epoch-028.ckpt
  hparams_yaml: lightning_logs/version_0/hparams.yaml
  accelerator: gpu
  devices: [0]
  eval_one: false  
  segment_batch_size: 4

defaults:
  - data
  - _self_
